"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/gollum_weta_workshop.glb 
Author: Emm (Scenario) (https://sketchfab.com/edemaistre)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gollum-weta-workshop-5de697f1593f4fc584563903ce09f717
Title: Gollum (Weta Workshop)
*/

import React, { MutableRefObject, use, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export default function Gollum() {
  const { nodes, materials }: any = useGLTF("/models/gollum_weta_workshop.glb");

  const mesh: MutableRefObject<any> = useRef();
  const timeline: MutableRefObject<any> = useRef();

  useFrame(() => {
    timeline.current = gsap.timeline();
    mesh.current.rotation.z += 0.01;

  });
  return (
    <group scale={25} dispose={null}>
      <mesh
        ref={mesh}
        geometry={nodes.Object_2.geometry}
        material={materials.material_1}
        rotation={[-1.5, 0, 3.8]}
        scale={1}
      />
    </group>
  );
}

useGLTF.preload("/models/gollum_weta_workshop.glb");
